### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by fabiorphp** [phansible/phansible#101]
Guys, to facilitate the deployment of the project, I propose is made integration with the Code Ship using Capistrano.

What do you think of that?

**Comment by naxhh** [comment]
I didn't say anithing but I was agree with erika's point of view.

In fact testing roles is the most tedious thing to do... since you need to test agains 3/4 distros and different combinations....

I've an idea of how to improve this a bit and that could be implemented inside the CI process.
But I agree that the current status is too fragile to add a CI system.
Also sometimes is a bit tedious to ask erika to deploy time to time.

But as she's normally online is not that bad.

I'm closing this just because there not so much to say. But feel free to re-open as always.
