### ISSUE TITLE
Option to enable verbose mode (-vvvv)

### ISSUE THREAD

**Issue by janimattiellonen** [phansible/phansible#166]
It would be nice to have an option to enable verbose mode (-vvvv) in Vagrantfile:

ansible.verbose = "vvvv"

Maybe even make it enabled by default and have the option to disable it. Verbose mode often provides better details on what went wrong and I use it almost constantly.

In fact, I'll see if I can whip up this setting myself :)

**Comment by janimattiellonen** [comment]
https://github.com/phansible/phansible/pull/167

**Comment by naxhh** [comment]
Hi! And thanks for giving this kind of feedback!

First of all would be grate if you can provide examples of when this idea you propose would be used.
This help us getting a better idea of why this should be added.

I've a few problems with this kind of features.
I'll try to explain them to make my point.

- Makes the UI more complex.
This is my first problem always. We would love to add a LOT of options and configurations.
But that can lead to a more challenging UX.
Right now we have a few roles and see how many options we have.
Imagine when we add verbosity, opening URL when finish provisioning, Windows system and a few other ideas of this kind that where rejected because this.

- Verbose level is for debugging.
I understand why you want it. of course is very useful when you are in a Dev environment when you have added a few lines in the roles.
But for me this is a secondary "problem" we face when working with the ansible set-up.
Phansible is more about set-up a PHP environment than the process/workflow that will come later.

If you need verbosity, of course add it.
And if everyone of us agree that this feature is THAT useful (I'm not saying is not) we will make it happen.
---

That said. Vagrantfile is normally used for dev so this is not at all a bad idea.
I like more the normal verbosity level (I'm not interested in SSH handshakes and that normally)
But if we opt to increase verbose level, maybe instead of adding to the UI we should put it directly in the template.

**Comment by janimattiellonen** [comment]
In my experience with Vagrant and Ansible, without -vvvv, many error messages are often very diffuse and kinda hiding some important details about the error. I often find myself having to enable verbose mode when provisioning. 
Of course we can put the line directly to the template but by providing it as an option in the wizard, we can limit the reasons why anyone would needto modify the vagrantfile. 
Currently the verbose mode is enabled by default. However, we can reverse it and make it disabled by default (user would have to check the box manually).

**Comment by naxhh** [comment]
I would like more thoughts here.
@erikaheidi @InFog @fabiorphp @sndpl @mikeSimonson

**Comment by mikeSimonson** [comment]
Based on my experience, I never had to use the verbose mode as the whole output of the provisioner is shown in case of a failure. I guess it highly depend on the use.
Maybe it's usefull for the beginners ?

**Comment by sndpl** [comment]
I think it's only use full for developers who are going to create new roles and not for the 'users' that will create a vagrant box to use it. So my thought is just add the following lines to the vagrant file:

```
# Uncomment the next line to get more verbose output from ansible
# ansible.verbose = "vvvv"
```

and maybe mention this 'debug' feature in the readme.

**Comment by InFog** [comment]
Already discussed and decided not to go with it. Ok to close :)
