### ISSUE TITLE
Multiple server configuration

### ISSUE THREAD

**Issue by NigelGreenway** [phansible/phansible#180]
Hi,

I have been using Vagrant and Phansible the past few days and it has been a rich resource of information, so thank you to all who have contributed.

My next step in this process is a multiple server configuration. Is it in the projects scope or roadmap to allow the addition of adding n web servers and n database server with a load balancer in the front and so on? In terms of complexity within configurations, it could be standard config for certain options maybe?

I have not thought about it too much at this stage as I wanted to put the idea out there first due to it's complexity.

\-\-
Cheers

**Comment by naxhh** [comment]
Hi!

Glad you found it useful, I think @erikaheidi will be happy about that!

About the multi-server thing. The idea is great. And providing a good UI to that will be amazing.

I don't think it's part of the roadmap because we have too much to do yet.
Like adding more roles, better testing and things like that.

Anyway I like the idea so implementing little steps to go that direction would be great.

I don't know what the rest of the team things about it :)

**Comment by InFog** [comment]
@NigelGreenway, it is a good idea, indeed, thanks for that :) But IMO it is too far away from Phansible's "mission".

Providing a multi-server env with load balance is not a simple task and should not (again, IMO) be done by automated tools.

I believe Phansible's target is to provide easy to use and portable development environments, not production ready environments.

I'm closing this one, but if any new ideas come up, or someone on the team thinks we should support this feature in the future, we still can discuss it :smile:
