### ISSUE TITLE
Add support for vagrant-cachier plugin

### ISSUE THREAD

**Issue by Ekstazi** [phansible/phansible#189]
Please add support for vagrant-cachier plugin that speed up provosion process. I add this functionality by adding thease lines to my `Vagrantfile`:
```ruby
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

```

**Comment by naxhh** [comment]
Hi,

I'll like to discuss bot requests (this and #188) here in the same issue. Because for me both have the same problems.

First let me thank you taking the time to recommend your workflow to us.
We always can learn from it, in fact I didn't know about any of this two plugins you are proposing.

When devs request us new features we always face this problem on where the limit should be.
Phansible has two main objectives:

The first one is to make as easy as possible to PHP devs to get a working playbook ready to Vagrant deploy and Production deploy.

Second one and maybe more important is that we try to approach ansible as easy as possible.
This means keeping roles and configurations easy to read and understand. Not adding "weird" behaviours or configurations in our roles or vagrant file.

In fact we had a long discussion about adding The which function (https://github.com/phansible/phansible/blob/master/Vagrantfile#L1) into our Vagrantfile even when was a very good WIN for us.

We saw that people dont really understand what this function does and, in fact, ourselves sometimes forgot about it and create bugs with new implementations (#112).

You now may be wondering why Im talking so much...
Well, we already rejected other proposals like this one because, even when they are good reasons to put it as default. We end up making our configurations harder to read and less atractive for developers that are starting out (keep in mind the project objectives)

That said, we are always open to discuss implementations of things that people consider are really great for them.

But right now, given the way you have proposed both plugins for me are a big NO-NO because of the things I've explained so far.

Will be great if you can explain more about this plugin in the task, explain what we win using it. Comparing times with and without it... and maybe we can agree in a point that this is amazing and should be in, and maybe we recommend users to install this plugin because you know, is amazing.

But all of this, is just my humble opinion.
Maybe @erikaheidi, @InFog, @fabiorphp or one of our @phansible/collaborators can bring a fresh and different view about this instead of mine.
I'll love to see more feedback related to this things :relaxed:

**Comment by Ekstazi** [comment]
You can find more details here http://fgrehm.viewdocs.io/vagrant-cachier

**Comment by InFog** [comment]
My two cents..

I think we have some nice wins implementing both proposals. Of course it will make things a little bit more complicated, but at the same time, a little bit better.

On the other hand I also think it's better to stick to defaults. So, if the user need a plugin to make things better, we don't implement. If it's a default option of vagrant, we implement.

Still, this is a very tricky decision to make. We don't want to scare new contributors by saying NO-NO to a lot of stuff, and at the same time we can not accept all good ideas.

Another solution regarding these proposals (and similar) is having a new file or session with these plugin related stuff and we can have a FAQ in the site explaining how they work, why we recommend them and where to get more information. Of course a proposal/PR would have to include such docs.

Let's wait for considerations for other contributors, but I'm curious about @fabiorphp and @erikaheidi's opinions.

**Comment by mikeSimonson** [comment]
I think that the cachier plugin is really a good one for which we ought to have a documentation page that explain how and why to set it up in vagrant.

Maybe later on when we have a test setup that works nicely, then we could have a basic phansible setup without those and a expert one with them, but that's not for tomorrow.

**Comment by InFog** [comment]
I think we can decide this by simply deciding whether to support plugins or not.

I vote for vanilla Vagrant/Ansible/[Any other tool we use]. If there are no thoughts about it, we can close this and #188.

**Comment by naxhh** [comment]
I vote for no plugins too. I think should be added by who wants them.

PD: Thanks for moving this and other issues @InFog

**Comment by InFog** [comment]
Let's close for now :)
