### ISSUE TITLE
What is ansible/windows.sh used for?

### ISSUE THREAD

**Issue by khromov** [phansible/phansible#255]
See topic.

**Comment by naxhh** [comment]
I didn't understand the "see topic" part.

windows.sh is used in the vagrant file to provision the machine when you don't have ansible installed in your host.

So, normally you have ansible in your machine. You do `vagrant up` an it will run ansible from your host connecting to the VM to provision.

But, if you don't have ansible it will run that script **inside** the VM. Provisioning with an ansible installed in the VM.

Hope this resolve your question. if not feel free to ask on gitter :)

**Comment by khromov** [comment]
Ah, misunderstanding on my part, I thought Ansible always ran inside the VM.

Thanks for the answer @naxhh

**Comment by naxhh** [comment]
This fact pop in a conversation with erika not so much ago... I was thinking if some documentation is needed in this regard. Because I'm afraid most of people that is new to ansible thinks the same way.

An one of the main benefits of ansible over other implementations is the fact that your server does not need any binary or agent to make the provisioning. Is just plain ssh.
