### ISSUE TITLE
constants for re-used values

### ISSUE THREAD

**Issue by designermonkey** [phansible/phansible#257]
Can we have the vagrantfile use constants for the reused values like IP address and hostname?

Also, is there any way to have these values placed into the yaml files too?

For occasions where I re-use the same set of files for new projects, I would like to be able to change values in one place and it apply to all uses.

**Comment by naxhh** [comment]
I'm not sure I've followed you on this.

The vagrantfile intends to present a dev machine for projects. But always tries to keep things simple so people feel confortable with them. Remember phansible is about learning ansible. The final objective was never a full orchestration UI.

I understand the need for constants and you can present some code about it. to see how it looks.
I don't get the ansible part.

**Comment by designermonkey** [comment]
Well, I didn't mention ansible in this, but what I was talking about was centralising repetitive values. I figured how to do it:

```ruby
require 'yaml'
data = YAML.load_file "ansible/vars/all.yml"
vars = data['vagrant']['vm']
```

With this in the top of the vagrant file, I can have the configuration values all in one place (the vars/all.yml file), so if I needed to quickly change the IP address for example, I wouldn't have to do that in more than one place.

Then, I can use those values in the vagrant file

```ruby
vars['hostname']
```

**Comment by naxhh** [comment]
I see the point better now. Still kind of not like it.

ping @phansible/core-dev for more opinions on this.

**Comment by debo** [comment]
@naxhh I can be naive and wrong on this but I'm inclined to think that whoever uses phansible will re-use the site to generate a new project rather than copy/paste folders and editing files, if they do so, it's just a couple of values in two files. I can see where @designermonkey is coming from but I think I would like to keep this in the nice to have features/PR welcome bucket rather than something the core team should actively work on.

**Comment by naxhh** [comment]
I do think the same way so, closing this for now.
