### ISSUE TITLE
nginx caches static files

### ISSUE THREAD

**Issue by HMAZonderland** [phansible/phansible#261]
I'm not completely sure where the issue resides, but it has something to do with `sendfile`, `tcp_nopush` and `tcp_nodelay`. I cannot figure out the right cocktail for these settings.

**Comment by naxhh** [comment]
Hi! I'm sorry but I don't see where I can help you.

As you can see here: https://github.com/phansible/role-nginx/blob/master/templates/default.tpl
The nginx role template is a very very simple file as boilerplate. We intend and encourage people to modify the generated zip as they want need.

**Comment by HMAZonderland** [comment]
Well since its Phansible's goal to "generate Vagrant + Ansible dev environments for PHP" caching kinda kills it. This has something to do with the combination of the parameters i've mentioned in my first post. So, by my opinion, the environment should be dev by default and not cache static files.

**Comment by naxhh** [comment]
The vagrantfile is a plus and not a goal of Phansible.

The true is that Phansible's goal is to teach PHP developers how to use ansible. And we encourage them to play with the generated files.

There's not yet here because we have a lot of work to do but the idea is to also provide other files aside of Vagrantfile. For deployment and stuff so I don't see the "dev by default" claim.

**Comment by sndpl** [comment]
I always add the following options to my nginx.conf:
```
        sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
```
To fix the problem you have :) The current role doesn't have a template for nginx.conf to fix this problem, so it should be added.

And if you want to read more about these settings, see: https://t37.net/nginx-optimization-understanding-sendfile-tcp_nodelay-and-tcp_nopush.html

**Comment by naxhh** [comment]
@sndpl feel free to add the PR to the nginx role :)
