### ISSUE TITLE
Issue when select php 5.4

### ISSUE THREAD

**Issue by joserprieto** [phansible/phansible#266]
When you select php 5.4, phansible generated:

in ansible/vars/all.yml

php:
    install: '1'
    ppa: php5-oldstable

in ansible/roles/php/tasks/main.yml

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

When ran the provisioning:

< TASK: php | Add ppa Repository >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

failed: [192.168.2.2] => {"failed": true}
msg: Invalid repository string: ppa:ondrej/php5-oldstable

FATAL: all hosts have already failed -- aborting
 ____________

Trying to add the ppa on the guest:

add-apt-repository ppa:ondrej/php5-oldstable
..
NOTE: Ubuntu 13.10 (and higher) won't be supported in the repository.  If you require PHP 5.4 use Ubuntu 12.04.x LTS.
..
; apt-get install -y language-pack-en-base
; LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php5-oldstable
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable
Press [ENTER] to continue or ctrl-c to cancel adding it

*note*: i changed the box to a debian 8 jessie
box-cutter/debian82-i386
But i think that it isn't the problem.

Many thanks.

**Comment by naxhh** [comment]
I think the problem is pretty clear:

```
NOTE: Ubuntu 13.10 (and higher) won't be supported in the repository. If you require PHP 5.4 use Ubuntu 12.04.x LTS.
```

I think we will be removing 5.4 for the next release.

**Comment by joserprieto** [comment]
The problem isn't resolved.

If you select Ubuntu 14.04 box, the page will disable the option for php version 5.4; only a few lines os jS, i think.

Regards.

**Comment by debo** [comment]
@joserprieto I think that's intended, only 12.04 allows PHP 5.4 as I'm understanding. Isn't that the case?

**Comment by naxhh** [comment]
As per the error: `If you require PHP 5.4 use Ubuntu 12.04.x LTS`

I understand that this is intended and we shouldn't add logic in phansible to take this case in account. Even more because we will remove 5.4 from phansible.

If you've an issue regarding ubuntu >13.03 and higher not supported by php 5.4 go and open an issue to ondrej work. But I'm pretty sure the answer will be no because 5.4 is considered an old version of php 5
https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable
