### ISSUE TITLE
warning: 'include' is deprecated, 'import_tasks' or 'include_tasks' should be used

### ISSUE THREAD

**Issue by MacDada** [phansible/phansible#304]
```
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.1.0).
```

```
    default: Running ansible-playbook...
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by MacDada** [comment]
I'm not Ansible expert and I don't really know the difference between `import_tasks` and `include_tasks`.

http://docs.ansible.com/ansible/latest/playbooks_reuse_includes.html#including-and-importing-task-files

Anyway, changing `include:` to `import_tasks:` worked for me.

**Comment by debo** [comment]
Hi @MacDada thanks for reporting the error. I do apologies if it took this long to get sorted but time to dedicate to Phansible it's been a bit scarse. I'm now back to actively work on it and the issue you highlighted was fixed in [this commit](https://github.com/phansible/role-php/commit/fc0b7c14cbf2c0ce7844a30ee4cb2d5bcdf41065). Keep in mind that because of the new architecture of Phansible this type of issues are often role specific so if you are to encounter further problems, and I'm sure you will, it would be great if you could file the bug against the proper role repo.

I'm going to close this issue as resolved but feel free to reply and keep the conversation going.

Thanks again for you contribution, I really appreciate it.
